'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.FAQs

    Partial Public Class FAQsCategories

        '''<summary>
        '''lstCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstCategory As Global.System.Web.UI.WebControls.DataList

        '''<summary>
        '''cmdAddNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddNew As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdGoBack control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdGoBack As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''panelAddEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelAddEdit As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''rowFaqCategoryId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowFaqCategoryId As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plCategoryId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCategoryId As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lblId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblId As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plCategoryName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCategoryName As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtCategoryName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCategoryName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqdCategoryName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqdCategoryName As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''plCategoryDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCategoryDescription As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtCategoryDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCategoryDescription As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqdCategoryDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqdCategoryDescription As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
