'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.FAQs

    Partial Public Class FAQs

        '''<summary>
        '''RadComboBoxCats control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadComboBoxCats As Global.Telerik.Web.UI.RadComboBox

        '''<summary>
        '''lstFAQs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstFAQs As Global.System.Web.UI.WebControls.DataList

        '''<summary>
        '''ObjectDataSourceCats control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ObjectDataSourceCats As Global.System.Web.UI.WebControls.ObjectDataSource
    End Class
End Namespace
