'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.FAQs

    Partial Public Class FAQs

        '''<summary>
        '''pnlShowCatagories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlShowCatagories As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''dnnListBoxCats control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dnnListBoxCats As Global.DotNetNuke.Web.UI.WebControls.DnnListBox

        '''<summary>
        '''chkCatagorie control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCatagorie As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lstFAQs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstFAQs As Global.System.Web.UI.WebControls.DataList
    End Class
End Namespace
