'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.FAQs

    Partial Public Class Settings

        '''<summary>
        '''lblShowCatagories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblShowCatagories As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkShowCatagories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowCatagories As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblDefaultSorting control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDefaultSorting As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpDefaultSorting control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpDefaultSorting As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblQuestionTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblQuestionTemplate As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtQuestionTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtQuestionTemplate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblAnswerTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAnswerTemplate As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtAnswerTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAnswerTemplate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblLoadingTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLoadingTemplate As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtLoadingTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLoadingTemplate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblAvailableTokens control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAvailableTokens As Global.System.Web.UI.UserControl

        '''<summary>
        '''lstAvailableTokens control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstAvailableTokens As Global.System.Web.UI.WebControls.ListBox
    End Class
End Namespace
